
%  DQNOA: A Problem-Adaptive Deep Q-Network Optimization Algorithm for Continuous and Engineering Problems
%  Mohammad-Reza Feizi-Derakhshi, Najibeh Farzi-Veijouyeh
%  Department of Electronic and Computer Engineering, University of Tabriz, Tabriz, Iran
% najibeh.farzi@gmail.com
% Generated by Najibeh Farzi-Veijouyeh, 2026
% Main paper:
% DQNOA: A Problem-Adaptive Deep Q-Network Optimization Algorithm for Continuous and Engineering Problems
% Cite:
% Feizi-Derakhshi, M.-R., & Farzi-Veijouyeh, N. (2026). DQNOA: A Problem-Adaptive Deep Q-Network Optimization Algorithm for Continuous and Engineering Problems. 
% Communications in Nonlinear Science and Numerical Simulation, 110502. https://doi.org/10.1016/j.cnsns.2026.110502 
% DOI: https://doi.org/10.1016/j.cnsns.2026.110502 
% _
% --------------------------------------------

function  [Convergence_curve, FEs_counts ,BestR, Fbest, fitness_history, position_history , Trajectories, it ,nPops]=DQNOA(F_index,CostFunction,VarMin, VarMax , nVar,Parameter,DisplayResults,fpt)%
%global   Max_FEs  bestStar
Max_FEs=Parameter.MaxFEs;
bestStar=Parameter.best;


%Constants
try Parameter.Gamma;
catch
    Parameter.Gamma=0.99;
end
p.gamma=Parameter.Gamma;
%Parameters
try Parameter.nPop;
catch
    Parameter.nPop=50;
end


%%DQN
NF=9;
% Define the number of neurons for each layer
hiddenSize = round(sqrt(nVar*NF));   % Number of hidden neurons
% Create a feedforward neural network with one hidden layer
net = feedforwardnet(hiddenSize, 'trainlm');
% Set activation functions for each layer
net.layers{1}.transferFcn = 'tansig';  % Hidden layer: Hyperbolic tangent sigmoid function
net.layers{2}.transferFcn = 'purelin'; % Output layer: Linear activation function
net.trainParam.showWindow = false; % Turn off display progress dialog.
net.inputs{1}.size = nVar;    
net.layers{2}.size = NF;    

VarMin=VarMin.*ones(1,nVar);
VarMax=VarMax.*ones(1,nVar);

try DisplayResults;
catch
    DisplayResults=0;
end
MAxPop=Parameter.nPop;
nPop=MAxPop;

dim=nVar;
NumIt=round(Max_FEs/nPop);
fitness_history=zeros(nPop,NumIt);
position_history=zeros(nPop,NumIt,nVar);
Trajectories=zeros(nPop,NumIt);
Convergence_curve=zeros(1,NumIt);
nPops=zeros(1,NumIt);
try isempty(fpt)
catch
    fpt=0;
end
mFES=0;
VarSize = [1 nVar];
%% Initialization
flag=0;
if flag==1
    X(1,:) = unifrnd(0, 1, VarSize);
    for i = 1:nPop
        % Initialize Solutions
        X(i+1,:) = 4* X(i,:).*(1- X(i,:)); %(Eq. 1)
    end
    for i = 1:nPop
        X(i,:)=mapping(X(i,:),dim,VarMax,VarMin);
        % Evaluation
        Costs(i,1) = CostFunction(X(i,:),F_index,dim);
         mFES=mFES+1;
    end
else
    X=initialization(nPop,dim,VarMax,VarMin);
    for i = 1:nPop
        % Evaluation
        Costs(i,1) = CostFunction(X(i,:),F_index,dim);
        mFES=mFES+1;
    end
end
p.VarMax=VarMax;
p.VarMin=VarMin;
p.A=NF;
p.nVar=nVar;
xcounter=1;
% min_epsilon=0.01;
% max_epsilon=0.99;
y=zeros(NF,2);
y(randi(NF),2)=1;%Q learning target
batchsize=200;
for i=1:2
    x(i,:)=dqnstate(X(i,:),p);
end
net1=net;
[net,~]=train(net,x',y); 

mk1=2;mk2=1;
% Initialize Best Cost History
[BestCost, index]= mink(Costs,mk2);
GlobalBest.X=X(index,:);
GlobalBest.Cost=Costs(index);

LocalBestsNum=1;
LBN=100;
LBX=zeros(LBN,nVar);
LBX(1,:)=GlobalBest.X;
it=1;
[Convergence_curve(it)] = BestCost(1);
fitness_history(:,it)=Costs;
if fpt==1
    position_history(:,it,:)=X;
    Trajectories(:,it)=X(:,1);
end

FEs_counts(it)=mFES;

%%NFV  Main Loop
it=2;
nPops(1)=nPop;
NXs=zeros(batchsize,nVar);rewards=zeros(1,batchsize);Actions=zeros(1,batchsize);
x=zeros(batchsize,nVar); 
BCosts=[];%nReapet=0;
while mFES<=Max_FEs
   
    epsilon=1-(exp(-0.5*mFES / Max_FEs));
     a2=-1-(mFES/Max_FEs); %% a2 linearly decreases from -1 to -2
    A = RandOrthMat(nVar,1e-12);
    Formula1s=ones(nPop,mk1);
    mrand=rand(1,nPop);
    DQNX=find(mrand<=epsilon);
    RandomF=1:nPop;
    RandomF(DQNX)=[]; 
    if ~isempty(DQNX)
        [Formula1DQN,  ~]=maxQ_NN(X(DQNX,:),net,p);
        Formula1s(DQNX,:)=Formula1DQN'*ones(1,mk1);
    end
    if ~isempty(RandomF)
        Formula1Random=round(1+rand([numel(RandomF) mk1])*(NF-1));
        Formula1s(RandomF,:)=Formula1Random;
    end
    
    LocalBest.Cost=inf;
    for i = 1:nPop
        l=(a2-1)*rand+1; 
        FI=round(1+rand([1 mk1])*(LocalBestsNum-1));     
        Formula1=Formula1s(i,:);    
        NXCostB=Inf;
        m=1-(mFES/Max_FEs);
        xr1=round(1+rand([nVar*mk1 3])*(nPop-1));
        NX = zeros(mk1, nVar);NXCost=zeros(1,mk1);
        for NXI=1:mk1
            Formula=Formula1(NXI);
            if Formula==2
                r1=round(1+rand*(nPop-1));
                r2=round(1+rand*(nPop-1));
                U=(X(index(1),:)-X(i,:)+X(r1,:)-X(r2,:))*A;
                U=rand.*U*A';
            end
            rr2=rand;
            for  j=1:nVar
                if rand<rand
                    xr=xr1((nVar*(NXI-1)+j),:);
                    switch Formula
                        case(1)
                            NX(NXI,j)=X(i,j)+rand*(GlobalBest.X(j)-X(i,j))+rand*(X(xr(1),j)-X(xr(2),j));
                        case(2)                           
                            NX(NXI,j)=X(i,j)+U(j);                           
                        case (3)
                            NX(NXI,j)=X(xr(3),j)+rand^2*(VarMax(j)-VarMin(j))+rand*(X(xr(1),j)-X(xr(2),j));
                        case (4)
                          alpha=cos(pi*rand)*m; 
                            NX(NXI,j)=X(i,j)+alpha*(LBX(FI(NXI),j)-X(xr(1),j));
                        case (5)
                            NX(NXI,j)=X(xr(1),j)*cos(l*pi*2)*m;
                        case(6)
                            NX(NXI,j)=X(i,j)+rand*(X(xr(1),j)-X(xr(2),j));
                        case (7)
                            NX(NXI,j)=LBX(FI(NXI),j)+(rr2*2-1)*m*(VarMin(j)+rand*(VarMax(j)- VarMin(j))); % Eq. (8)
                        case (8)
                            if rand<rand
                                NX(NXI,j)=VarMin(j)+rand*(VarMax(j)- VarMin(j));
                            else
                                NX(NXI,j)=X(i,j);
                            end
                        case(9)
                            NX(NXI,j)=GlobalBest.X(j)+rand*(X(xr(1),j)-X(xr(2),j)); 
                            
                        case (10)
                            NX(NXI,j)=X(i,j)+rand*plevy(j)*(X(FI(NXI),j)-X(i,j))++rand*(X(xr(1),j)-X(xr(2),j));
            
                    end
                else
                    NX(NXI,j)=X(i,j);
                end
                
                if  NX(NXI,j)>VarMax(j) || NX(NXI,j)<VarMin(j)
                    NX(NXI,j)=VarMin(j)+rand*(VarMax(j)-VarMin(j));
                end
            end
            NXCost(NXI)=CostFunction(NX(NXI,:),F_index,dim);
            mFES=mFES+1;
            
            if Costs(i)<NXCost(NXI)
                reward=-1;      
            elseif Costs(i)>NXCost(NXI)                
                reward=1;
            else 
                reward=0;
            end 
            Action=Formula;
            x(xcounter,:)=dqnstate(X(i,:),p); 
            NXs(xcounter,:)=NX(NXI,:);
            rewards(xcounter)= reward;
            Actions(xcounter)= Action;
            xcounter=xcounter+1;
            if mod(xcounter-1,batchsize)==0
                [~, Qmax_NN]=maxQ_NN(NXs,net,p);
                y=zeros(NF,batchsize);
                for kk=1:batchsize
                y( Actions(kk),kk)=rewards(kk)+p.gamma*(Qmax_NN(kk));%Q learning target
                end
                if batchsize<10000
                    batchsize=batchsize+200;
                end
                try
                [net1,~]= adapt(net1,x',y); %To update the weights
                catch
                [net1,~]=train(net1,x',y); %To update the weights
                end
                clear net;
                net=net1;
               NXs=zeros(batchsize,nVar);rewards=zeros(1,batchsize);
               x=zeros(batchsize,nVar); 
                xcounter=1;
            end
            if NXCost(NXI)<NXCostB
                NXCostB=NXCost(NXI);
                NXB=NX(NXI,:);
            end
        end
         if NXCostB<LocalBest.Cost
            LocalBest.Cost=NXCostB;
            LocalBest.X=NXB;
        end
        if NXCostB<Costs(i)
             if NXCostB<GlobalBest.Cost
                GlobalBest.Cost=NXCostB;
                GlobalBest.X=NXB;
            end     
            Costs(i)=NXCostB;
            X(i,:)=NXB;
        end
    end
    
     if LocalBestsNum<LBN        
        LocalBestsNum=LocalBestsNum+1;
        LBX(LocalBestsNum,:)=LocalBest.X;
    else
        hh=randi(LBN);
        LBX(hh,:)=LocalBest.X;
    end
    [X,Costs]=OmitExtra(Costs,X);
    nPop = round(4 + (1 - (mFES / Max_FEs)) * (MAxPop - 4)) ;
    
    
    EX=[];ECosts=[];flag=0;
    
    np1=numel(Costs);
    for i=1:(nPop-np1)
        EX(i,:) = mean(X,1).*rand;
        for j=1:nVar
            if  EX(i,j)>VarMax(j) || EX(i,j)<VarMin(j)
                EX(i,j)=VarMin(j)+rand*(VarMax(j)-VarMin(j));
            end
        end
        ECosts(i,1) = CostFunction(EX(i,:),F_index,dim);
        flag=1;
        mFES=mFES+1;
    end
    
    X=[X; EX];
    Costs=[Costs ;ECosts];
    if flag==1
        [~ ,ic]=sort(Costs);
        X=X(ic,:);
        Costs=Costs(ic,:);
    end
    X=X(1:nPop,:);
    Costs=Costs(1:nPop);
    BestCost=Costs(1);
    index=1:mk2 ;
    Convergence_curve(it)=min([BCosts ;BestCost]);
     if fpt==1
        fitness_history(1:nPop,it)=Costs;
        position_history(1:nPop,it,:)=X;
        Trajectories(1:nPop,it)=X(:,1);
        nPops(it)=nPop;
    end
    FEs_counts(it)=mFES;
    
    Fbest=Convergence_curve(it);
    if DisplayResults==1
        % Display Iteration Information
        disp(['Iteration ' num2str(it-1) ', mFEs=' num2str(mFES) ': Best Cost = ' num2str(Convergence_curve(it))]);
    end
    if mFES>=Max_FEs,break;end
    if Fbest==bestStar
        break
    end
    
    
    
    it=it+1;
    
end
nPops(end+1)=nPop;
if it<NumIt
    FEs_counts(it:NumIt)=mFES;
    Convergence_curve(it:NumIt)=Convergence_curve(it);
    for j=1:nPop
        if fpt==1
            fitness_history(j,it:NumIt)=fitness_history(j,it);
        end
    end
end
%% Results
Fbest=BestCost;
BestR=X(1,:);

display(['The best solution obtained by DQNOA is : ', num2str(BestR)]);
display(['The best optimal value of the objective funciton found by DQNOA is : ', num2str(Fbest,10)]);
display(['iteration:',num2str(it)]);
disp(sprintf('--------------------------------------'));


L = length(Convergence_curve);
ind = round((1:NumIt)*L/NumIt);
Convergence_curve = Convergence_curve(ind);
FEs_counts=FEs_counts(ind);

L = size(Trajectories,2);
ind = round((1:NumIt)*L/NumIt);
Trajectories=Trajectories(:,ind);
position_history=position_history(:,ind,:);
fitness_history= fitness_history(:,ind);
nPops=nPops(ind);
it=min(numel(nPops),it);
end
function Positions=initialization(SearchAgents_no,dim,ub,lb)

Boundary_no= size(ub,2); % numnber of boundaries

% If the boundaries of all variables are equal and user enter a signle
% number for both ub and lb
if Boundary_no==1
    Positions=rand(SearchAgents_no,dim).*(ub-lb)+lb;
end

% If each variable has a different lb and ub
if Boundary_no>1
    for i=1:dim
        ub_i=ub(i);
        lb_i=lb(i);
        Positions(:,i)=rand(SearchAgents_no,1).*(ub_i-lb_i)+lb_i;
    end
end
end
function [X,Costs]=OmitExtra(Costs,X)
[~, ic]=unique(Costs);
%[CG ic]=unique(X, 'rows');
X=X(ic,:);
Costs=Costs(ic,:);
end
function MX=mapping(X,dim,ub,lb)
if numel(ub)==1
    ub=ones(1,dim)*ub;
    lb=ones(1,dim)*lb;
end
for i=1:dim
    ub_i=ub(i);
    lb_i=lb(i);
    MX(:,i)=X(i).*(ub_i-lb_i)+lb_i; %(Eq. 2)
end
end
function R = RandOrthMat(n, t)
% orthogonal matrix approx
R = eye(n);
l = randperm(n);
% t = 1e-8;
for ii = 1:floor(n/2)
    i = 2*(ii-1)+1;
    R(l(i),l(i)) = sin(t);
    R(l(i+1),l(i+1)) = sin(t);
    R(l(i),l(i+1)) = cos(t);
    R(l(i+1),l(i)) = -cos(t);
end
end
%maps state-action pair into dqn state (which varies between -1 and 1)
function [x]=dqnstate(state,p)
x=(2*(state-p.VarMin)./(p.VarMax-p.VarMin))-1;
end
%Finds max Qvalue and corresponding optimal action for a state, given some value function weights
function [a, Qmax]=maxQ_NN(state,net,p) 
      
ALLX=((2*(state-p.VarMin)./(p.VarMax-p.VarMin))-1)';   
try
b=net.b;
ALLq = feval(net.layers{2}.transferFcn,  net.LW{2,1} *  feval(net.layers{1}.transferFcn, net.IW{1,1}  * ALLX + b{1}) + b{2});  
catch
    ALLq=net(ALLX);
end
    k=1; 
for j=1:size(ALLq,2)
    q=ALLq(:,j); 
    max_arg=find(q==max(q));
    L=numel(max_arg);
    if L>1
        max_arg=max_arg(randi(L));
    end
    a(k)=max_arg;
    Qmax(k)=q(max_arg);
    k=k+1;
end




end

