%  DQNOA: A Problem-Adaptive Deep Q-Network Optimization Algorithm for Continuous and Engineering Problems
%
% Generated by Najibeh Farzi-Veijouyeh, 2026
% Main paper:
% DQNOA: A Problem-Adaptive Deep Q-Network Optimization Algorithm for Continuous and Engineering Problems
%  
% DOI: ...
% _
% --------------------------------------------
% fobj = @YourCostFunction
% dim = number of your variables
% MaxFEs = maximum number of fitness evaluations
% N = number of solutions
% lb=[lb1,lb2,...,lbn] where lbn is the lower bound of variable n
% ub=[ub1,ub2,...,ubn] where ubn is the upper bound of variable n
% ---------------------------------------------------------
%____________________________________________________



clear all
clc
%rng(10)   
format long

F_index=1; % F1:F29--> 1:29
Function_name=strcat('F',num2str(F_index));

DisplayResults=0;
[lb,ub,dim,bestStar]=test_functions_range(F_index);
fobj=@test_functions;

Parameter.MaxFEs=dim*10000; % Maximum number of fitness evaluations
Parameter.nPop=30;    % Number of initial solutions 
Parameter.Gamma=0.3;
Parameter.best=inf;

if F_index>=24 &&F_index<=29 %composite functions
    global initial_flag
    initial_flag=0;
     clear fun_num func o sigma lamda bias M 
end

[Convergence_curve,FEs_counts,X ,Fbest]=DQNOA(F_index,fobj,lb, ub , dim,Parameter,DisplayResults,0);

% Convergence curve
semilogy(FEs_counts,Convergence_curve,'Color','r')
title('Objective space')
xlabel('FEs');
ylabel('Best score obtained so far');



